package:
  name: knotty
  version: "1.0.0"

source:
  path: ..
  # git_url: https://github.com/HosnaJabbari/Knotty.git
  # git_rev: (latest tag)

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.1
  host:
    - libstdcxx-ng    # [linux]
    - libcxx          # [osx]
  run:
    - libstdcxx-ng    # [linux]
    - libcxx          # [osx]

about:
  home: https://github.com/HosnaJabbari/Knotty
  summary: "MFE-based RNA secondary structure prediction with pseudoknots."
  description: |
    Knotty is a computational tool for predicting RNA secondary structures, 
    including pseudoknotted configurations, using a Minimum Free Energy (MFE) 
    approach. It allows users to input RNA sequences and receive predicted 
    structural conformations optimized for thermodynamic stability.

    The software is implemented in C++ and requires a C++11-compatible compiler 
    along with CMake (≥3.1) for installation. Knotty is designed to run on Linux 
    and macOS platforms and provides a command-line interface for flexible usage.

    For installation, usage instructions, and additional details, visit:
    https://github.com/HosnaJabbari/Knotty

  dev_url: https://github.com/HosnaJabbari/Knotty

extra:
  recipe-maintainers:
    - PointlessUser

test:
  commands:
    - knotty --help